openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: TestEndpoint contract
    url: ""
paths:
  /TestEndpoint: {}
components:
  schemas:
    RefType:
      type: object
    TestType:
      type: object
      properties:
        testAttribute1:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        testAttribute2:
          $ref: '#/components/schemas/RefType'
        testAttribute3:
          type: string
          description: Generic parameter
        list:
          type: object
          properties:
            listAttribute1:
              type: string
              description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                target="_blank">Data Element</a>
            listAttribute2:
              type: integer
              description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                target="_blank">Data Element</a>
              format: int32
        subTree:
          type: object
          properties:
            subTreeAttribute:
              type: string
              description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                target="_blank">Data Element</a>
