openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: TestEndpoint contract
    url: ""
paths:
  /TestEndpoint:
    post:
      tags:
      - TestEndpoint
      summary: o1
      description: ""
      operationId: o1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestType'
      responses:
        "200":
          description: o1 successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestType1'
components:
  schemas:
    TestType:
      type: object
      properties:
        testAttribute:
          type: array
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          items:
            type: string
    TestType1:
      type: object
      properties:
        testAttribute:
          type: array
          items:
            $ref: '#/components/schemas/TestType'
    TestType2:
      type: object
      properties:
        testAttribute1:
          type: array
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          items:
            type: string
        testAttribute2:
          minItems: 1
          type: array
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          items:
            type: string
        testAttribute3:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          nullable: true
        testAttribute4:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          nullable: false
