openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: The role of this endpoint is not specified.
    url: ""
paths:
  /TestEndpoint: {}
components:
  schemas:
    TestType:
      type: object
