openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: The role of this endpoint is not specified.
    url: ""
paths:
  /TestEndpoint: {}
components:
  schemas:
    RefType:
      type: object
    TestType:
      type: object
      properties:
        testAttribute1:
          type: string
        testAttribute2:
          $ref: '#/components/schemas/RefType'
        testAttribute3:
          type: object
        list:
          type: object
          properties:
            listAttribute1:
              type: string
            listAttribute2:
              type: integer
              format: int32
        subTree:
          type: object
          properties:
            subTreeAttribute:
              type: string
