openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: TestEndpoint contract
    url: ""
paths:
  /TestEndpoint: {}
components:
  schemas:
    TestType:
      type: array
      items:
        type: object
        properties:
          testAttribute1:
            type: string
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
          testAttribute2:
            type: array
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
            items:
              type: string
