openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: The role of this endpoint is Information Holder Resource pattern
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    put:
      tags:
      - TestEndpoint
      summary: Puts a new test object (inlined data)
      description: Puts a new test object (inlined data)
      operationId: putTest
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                someText:
                  type: string
      responses:
        "200":
          description: putTest successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  flag:
                    type: boolean
components:
  schemas: {}
