openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: TestEndpoint contract, Information Holder Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    put:
      tags:
      - TestEndpoint
      summary: putTest (Puts a new test object (inlined data) method)
      description: Puts a new test object (inlined data)
      operationId: putTest
      requestBody:
        description: Message payload (content)
        content:
          application/json:
            schema:
              type: object
              properties:
                someText:
                  type: string
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
              description: request body elements for putTest
      responses:
        "200":
          description: putTest successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  flag:
                    type: boolean
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
components:
  schemas: {}
