openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: TestEndpoint contract, Information Holder Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    post:
      tags:
      - TestEndpoint
      summary: createTest (SomeOtherResponsibility method)
      description: SomeOtherResponsibility
      operationId: createTest
      requestBody:
        description: Message payload (content)
        content:
          application/json:
            schema:
              type: object
              properties:
                booleanFlag:
                  type: boolean
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
              description: request body elements for createTest
      responses:
        "200":
          description: createTest successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
components:
  schemas:
    Test:
      type: object
      properties:
        longReturnCode:
          type: number
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
