openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: TestEndpoint contract, Information Holder Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    get:
      tags:
      - TestEndpoint
      summary: getTest
      description: ""
      operationId: getTest
      parameters:
      - name: attr1
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
      - name: attr2
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: array
          items:
            minItems: 1
            type: array
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
            items:
              type: string
      responses:
        "200":
          description: getTest successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
components:
  schemas:
    Test:
      type: object
      properties:
        anonymous1:
          type: number
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
