openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: The role of this endpoint is Information Holder Resource pattern
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    post:
      tags:
      - TestEndpoint
      summary: Creates new Test object
      description: Creates new Test object
      operationId: createTest
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                attr1:
                  type: string
      responses:
        "200":
          description: no return value
          content: {}
components:
  schemas: {}
