openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: TestEndpoint contract, Information Holder Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    post:
      tags:
      - TestEndpoint
      summary: postTest (Creates new Test object method)
      description: Creates new Test object
      operationId: postTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestData1'
      responses:
        "200":
          description: no return value
          content: {}
    patch:
      tags:
      - TestEndpoint
      summary: patchTest (Updates a Test object partially method)
      description: Updates a Test object partially
      operationId: patchTest
      responses:
        "200":
          description: patchTest successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestData2'
components:
  schemas:
    TestData1:
      type: object
      properties:
        testData1:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
    TestData2:
      type: object
      properties:
        idOnly:
          type: string
          description: Generic parameter
    TestData3:
      type: object
