openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: The role of this endpoint is Information Holder Resource pattern
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    get:
      tags:
      - TestEndpoint
      description: unspecified operation responsibility
      operationId: getTest
      parameters:
      - name: attr1
        in: query
        required: true
        schema:
          type: string
      - name: attr2
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getTest successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
components:
  schemas:
    Test:
      type: object
      properties:
        anonymous1:
          type: number
