openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: The role of this endpoint is Information Holder Resource pattern
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    post:
      tags:
      - TestEndpoint
      summary: SomeOtherResponsibility
      description: SomeOtherResponsibility
      operationId: createTest
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                booleanFlag:
                  type: boolean
      responses:
        "200":
          description: createTest successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
components:
  schemas:
    Test:
      type: object
      properties:
        longReturnCode:
          type: number
