openapi: 3.0.1
info:
  title: MAPDecoratorAndMIMETest
  description: PUBLIC_API FRONTEND_INTEGRATION
  version: "1.0"
servers:
- url: https://some.sample.domain/mvcEndpoint
tags:
- name: FlexibleAndAdaptiveAPIProvider-self
  externalDocs:
    description: MultiRepresentationResource contract, Processing Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/ProcessingResource.html
paths:
  /self:
    summary: activity-oriented endpoint
    put:
      tags:
      - FlexibleAndAdaptiveAPIProvider-self
      summary: testOperation1 (write only method)
      description: '[State Creation Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateCreationOperation.html).'
      operationId: self-testOperation1
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/SampleDTOType'
          application/json:
            schema:
              $ref: '#/components/schemas/SampleDTOType'
      responses:
        "200":
          description: testOperation1 successful execution
          content:
            vnd.application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleDTOType'
            plain/text:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleDTOType'
    post:
      tags:
      - FlexibleAndAdaptiveAPIProvider-self
      summary: testOperation2 (read only method)
      description: '[Retrieval Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/RetrievalOperation.html).'
      operationId: self-testOperation2
      requestBody:
        content:
          vnd.application/json:
            schema:
              type: object
              properties:
                expecting:
                  type: integer
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
                  format: int32
          vnd.application/xml:
            schema:
              type: object
              properties:
                expecting:
                  type: integer
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
                  format: int32
      responses:
        "200":
          description: testOperation2 successful execution
          content:
            vnd.application/xml:
              schema:
                type: object
                properties:
                  deliveringSomeData:
                    type: string
                    description: Generic parameter
            plain/text:
              schema:
                type: object
                properties:
                  deliveringSomeData:
                    type: string
                    description: Generic parameter
components:
  schemas:
    SampleDTOType:
      type: object
      properties:
        data:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
          nullable: true
        formats:
          minItems: 1
          type: array
          description: <<Wish_List>> <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
          items:
            type: string
