openapi: 3.0.1
info:
  title: HTTPBindingOptionsDemo
  version: "1.0"
servers:
- url: /endpoint1
- url: /endpoint21
- url: /endpoint22
- url: /endpoint42
tags:
- name: NameHeuristicEndpointProvider1-self1
  externalDocs:
    description: HeuristicEndpoint1 contract, Information Holder Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
- name: NameHeuristicEndpointProvider21-self2
  externalDocs:
    description: HeuristicEndpoint2 contract, Processing Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/ProcessingResource.html
- name: NameHeuristicEndpointProvider22-self3
  externalDocs:
    description: HeuristicEndpoint2 contract, Processing Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/ProcessingResource.html
- name: NameHeuristicEndpointProvider42-self
  externalDocs:
    description: HeuristicEndpoint3 contract, "Another Role (not in MAP)" (non-pattern
      role) role
    url: ""
paths:
  /self1:
    summary: general data-oriented endpoint
    get:
      tags:
      - NameHeuristicEndpointProvider1-self1
      summary: createSomething (POST method)
      description: POST
      operationId: self1-createSomething
      parameters:
      - name: listOfBasicAtomicParameterTypes
        in: query
        description: Type reference listOfBasicAtomicParameterTypes
        schema:
          $ref: '#/components/schemas/ListOfBasicAtomicParameterTypes'
      responses:
        "200":
          description: createSomething successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericParameterP'
  /self2:
    summary: activity-oriented endpoint
    post:
      tags:
      - NameHeuristicEndpointProvider21-self2
      summary: readSomething (HEAD method)
      description: HEAD
      operationId: self2-readSomething
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfBasicAtomicParameterTypes'
      responses:
        "200":
          description: readSomething successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericParameterP'
  /self3:
    summary: activity-oriented endpoint
    post:
      tags:
      - NameHeuristicEndpointProvider22-self3
      summary: readSomething (HEAD method)
      description: HEAD
      operationId: self3-readSomething
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfBasicAtomicParameterTypes'
      responses:
        "200":
          description: readSomething successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericParameterP'
  /self:
    summary: 'main responsibility: "Another Role (not in MAP)"'
    get:
      tags:
      - NameHeuristicEndpointProvider42-self
      summary: putSomething
      description: ""
      operationId: self-putSomething
      parameters:
      - name: Parameter1
        in: query
        description: Type reference null
        schema:
          $ref: '#/components/schemas/ListOfBasicAtomicParameterTypes'
      responses:
        "200":
          description: putSomething successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericParameterP'
  /HeuristicEndpoint4:
    put:
      tags:
      - HeuristicEndpoint4
      summary: updateSomething (PUT method)
      description: PUT
      operationId: updateSomething
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfBasicAtomicParameterTypes'
      responses:
        "200":
          description: updateSomething successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericParameterP'
    patch:
      tags:
      - HeuristicEndpoint4
      summary: patchSomething
      description: ""
      operationId: patchSomething
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfBasicAtomicParameterTypes'
      responses:
        "200":
          description: patchSomething successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericParameterP'
  /HeuristicEndpoint5:
    post:
      tags:
      - HeuristicEndpoint5
      summary: removeSomething (POST method)
      description: POST
      operationId: removeSomething
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfBasicAtomicParameterTypes'
      responses:
        "200":
          description: removeSomething successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericParameterP'
    delete:
      tags:
      - HeuristicEndpoint5
      summary: deleteSomething
      description: ""
      operationId: deleteSomething
      parameters:
      - name: Parameter2
        in: query
        description: Type reference null
        schema:
          $ref: '#/components/schemas/ListOfBasicAtomicParameterTypes'
      responses:
        "200":
          description: deleteSomething successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericParameterP'
components:
  schemas:
    GenericParameterP:
      type: object
    ListOfBasicAtomicParameterTypes:
      type: object
      properties:
        dataString:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        metadataString:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
        intIdentifier:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
        stringLink:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/LinkElement"
            target="_blank">Link Element</a>
    PersonAsFlatParamaterTree:
      type: object
      properties:
        person:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        street:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        zip:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
        city:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        phoneNumbers:
          minItems: 1
          type: array
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          items:
            type: string
