openapi: 3.0.1
info:
  title: RESTBucksHypermediaAPI
  version: '"Maturity Level 3 (HATEOAS), example Version 0.2"'
servers:
- url: http://restbucks.com/order
tags:
- name: RESTBucksProvider-RESTBucksHome
  externalDocs:
    description: OrderManagementEndpoint contract, Processing Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/ProcessingResource.html
- name: RESTBucksProvider-Orders
  externalDocs:
    description: OrderManagementEndpoint contract, Processing Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/ProcessingResource.html
- name: RESTBucksProvider-PaymentResource
  externalDocs:
    description: OrderManagementEndpoint contract, Processing Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/ProcessingResource.html
- name: RESTBucksProvider-ReceiptResource
  externalDocs:
    description: OrderManagementEndpoint contract, Processing Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/ProcessingResource.html
paths:
  /RESTBucksHome:
    summary: activity-oriented endpoint
    post:
      tags:
      - RESTBucksProvider-RESTBucksHome
      summary: placeOrder (POST method)
      description: POST
      operationId: RESTBucksHome-placeOrder
      requestBody:
        content:
          application/vnd.order+json:
            schema:
              $ref: '#/components/schemas/OrderDTO'
          application/vnd.restbucks.order+xml:
            schema:
              $ref: '#/components/schemas/OrderDTO'
      responses:
        "200":
          description: placeOrder successful execution
          content:
            application/vnd.restbucks.payment+xml:
              schema:
                type: object
                properties:
                  oid:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                      target="_blank">Id Element</a>
                    format: int32
            application/vnd.restbucks.order-payment+json:
              schema:
                type: object
                properties:
                  oid:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                      target="_blank">Id Element</a>
                    format: int32
          links:
            payment:
              operationId: RESTBucksHome-acceptPayment
              parameters:
                payment: PaymentDTO
                resource: PaymentResource
                verb: POST
                cmt: PaymentRepresentationJSON
              description: 'Targeted operation: acceptPayment'
            extPayment:
              operationId: RESTBucksHome-payExternally
              parameters:
                extPayment: PaymentDTO
                resource: PaymentResource
                verb: POST
                cmt: PaymentRepresentationJSON
              description: 'Targeted operation: payExternally'
              server:
                url: PaymentServerAddress
            compensatingOperation:
              operationId: cancelOrder
  /{id}:
    summary: activity-oriented endpoint
    get:
      tags:
      - RESTBucksProvider-Orders
      summary: get (read only method)
      description: '[Retrieval Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/RetrievalOperation.html).'
      operationId: Orders-get
      parameters:
      - name: id
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
          target="_blank">Id Element</a>
        required: true
        schema:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
      responses:
        "200":
          description: get successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
    put:
      tags:
      - RESTBucksProvider-Orders
      summary: updateOrder (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: Orders-updateOrder
      requestBody:
        content:
          application/vnd.restbucks.order-payment+json:
            schema:
              $ref: '#/components/schemas/OrderDTO'
      responses:
        "200":
          description: updateOrder successful execution
          content:
            application/vnd.restbucks.order+json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
                    format: int32
          links:
            self:
              operationId: unknownOperation
              parameters:
                resource: Orders
                verb: POST
                cmt: OrderRepresentationJSON
            payment:
              operationId: Orders-acceptPayment
              parameters:
                payment: PaymentDTO
                resource: PaymentResource
                verb: POST
                cmt: PaymentRepresentationJSON
              description: 'Targeted operation: acceptPayment'
            extPayment:
              operationId: Orders-payExternally
              parameters:
                extPayment: PaymentDTO
                resource: PaymentResource
                verb: POST
                cmt: PaymentRepresentationJSON
              description: 'Targeted operation: payExternally'
              server:
                url: PaymentServerAddress
    delete:
      tags:
      - RESTBucksProvider-Orders
      summary: cancelOrder (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: Orders-cancelOrder
      parameters:
      - name: id
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
          target="_blank">Id Element</a>
        required: true
        schema:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
      responses:
        "200":
          description: cancelOrder successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
    patch:
      tags:
      - RESTBucksProvider-Orders
      summary: updateAmount (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: Orders-updateAmount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newAmount:
                  type: integer
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
                  format: int32
      responses:
        "200":
          description: updateAmount successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
                    format: int32
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
  /payment/{id}:
    summary: activity-oriented endpoint
    put:
      tags:
      - RESTBucksProvider-PaymentResource
      summary: acceptPayment (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: PaymentResource-acceptPayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentDTO'
      responses:
        "200":
          description: acceptPayment successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
          links:
            orderPaidAndReadyForPickUpAndAndDrinking:
              operationId: unknownOperation
              parameters:
                resource: Orders
                verb: POST
                cmt: OrderRepresentationJSON
        x-743:
          description: n/a
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                      target="_blank">Id Element</a>
                  info:
                    type: string
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
      security:
      - OnlyAuthenticatedShoppers: []
    post:
      tags:
      - RESTBucksProvider-PaymentResource
      summary: prepareOrderViaBarista (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: PaymentResource-prepareOrderViaBarista
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                    target="_blank">Id Element</a>
                  format: int32
      responses:
        "200":
          description: prepareOrderViaBarista successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
          links:
            self:
              operationId: unknownOperation
              parameters:
                resource: Orders
                verb: POST
                cmt: OrderRepresentationJSON
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
  /receipt/{id}:
    summary: activity-oriented endpoint
    patch:
      tags:
      - RESTBucksProvider-ReceiptResource
      summary: handOutAndConcludeProcess (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: ReceiptResource-handOutAndConcludeProcess
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                    target="_blank">Id Element</a>
                  format: int32
      responses:
        "200":
          description: handOutAndConcludeProcess successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
          links:
            forHereOrToGo:
              operationId: ReceiptResource-print
              parameters:
                resource: RESTBucksHome
                verb: POST
                cmt: ReceiptRepresentationJSON
        x-743:
          description: n/a
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                      target="_blank">Id Element</a>
                  info:
                    type: string
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                      target="_blank">Data Element</a>
      security:
      - OnlyAuthenticatedShoppers: []
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
components:
  schemas:
    OrderDTO:
      minItems: 1
      type: array
      items:
        type: object
        properties:
          milk:
            type: string
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
          size:
            type: string
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
          drink:
            type: string
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
          amount:
            type: integer
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
            format: int32
    PaymentDTO:
      type: object
      properties:
        means:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        authToken:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: binary
        amount:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
  securitySchemes:
    OnlyAuthenticatedShoppers:
      type: http
      description: ba
      scheme: basic
