openapi: 3.0.1
info:
  title: HTTPBindingWithReportAndPolicy
  version: "1.0"
servers:
- url: /mySampleHTTPEndpoint
tags:
- name: HelloHTTPEndpointNoBinding2-Home
  externalDocs:
    description: ReportAndPolicyEnabledPortType contract
    url: ""
paths:
  /Home:
    get:
      tags:
      - HelloHTTPEndpointNoBinding2-Home
      summary: getOperation
      description: ""
      operationId: Home-getOperation
      parameters:
      - name: aQueryParameter
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
      responses:
        "200":
          description: getOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedResponseDTR'
        "500":
          description: SomeExtraErrorReportText
          content:
            application/json:
              schema:
                type: object
                properties:
                  e500:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
                      target="_blank">Metadata Element</a>
                    format: int32
    put:
      tags:
      - HelloHTTPEndpointNoBinding2-Home
      summary: putOperation
      description: ""
      operationId: Home-putOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatParameterTree'
      responses:
        "200":
          description: putOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedResponseDTR'
        "502":
          description: SomeExtraErrorReportText
          content:
            application/json:
              schema:
                type: object
                properties:
                  e502:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
                      target="_blank">Metadata Element</a>
                    format: int32
      security:
      - BasicAuthenticationSample2: []
    post:
      tags:
      - HelloHTTPEndpointNoBinding2-Home
      summary: createOperation
      description: ""
      operationId: Home-createOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NestedParameterTree'
      responses:
        "200":
          description: createOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlatResponseDTR'
      security:
      - BasicAuthenticationSample: []
    patch:
      tags:
      - HelloHTTPEndpointNoBinding2-Home
      summary: patchOperation
      description: ""
      operationId: Home-patchOperation
      parameters:
      - name: customHeader1
        in: header
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
      - name: customHeader2
        in: header
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatParameterTree'
      responses:
        "200":
          description: patchOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlatParameterTree'
components:
  schemas:
    FlatParameterTree:
      type: object
      properties:
        id:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
        md:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
        dInt:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
        lString:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/LinkElement"
            target="_blank">Link Element</a>
        dLong:
          type: number
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        anonymous1:
          type: boolean
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
    NestedParameterTree:
      type: object
      properties:
        npt1:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        npt2:
          $ref: '#/components/schemas/FlatParameterTree'
    FlatResponseDTR:
      type: object
      properties:
        fr1:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        fr2:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
    NestedResponseDTR:
      type: object
      properties:
        r1:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
        r2:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/LinkElement"
            target="_blank">Link Element</a>
        anonymous2:
          $ref: '#/components/schemas/FlatResponseDTR'
    ErrorReport:
      type: object
      properties:
        code:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
        message:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
          format: int32
    Credentials:
      type: object
      properties:
        user:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
        password:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
          format: binary
  securitySchemes:
    BasicAuthenticationSample:
      type: apiKey
      name: api_key
      in: header
    BasicAuthenticationSample2:
      type: openIdConnect
      openIdConnectUrl: http://tbc.tbc
