openapi: 3.0.1
info:
  title: CRUDVerbAndDataTypeMappingTest
  version: "1.0"
servers:
- url: https://some.sample.domain/crudApiEndpoint
tags:
- name: Sample_CRUD_APIProvider-Home
  externalDocs:
    description: SampleEntityInformationHolder contract
    url: ""
paths:
  /Home:
    get:
      tags:
      - Sample_CRUD_APIProvider-Home
      summary: get
      description: ""
      operationId: Home-get
      parameters:
      - name: dto2
        in: query
        style: deepObject
        explode: true
        schema:
          type: array
          items:
            type: object
            properties:
              dtoKey:
                type: integer
                description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                  target="_blank">Id Element</a>
                format: int32
                nullable: true
              dto1Nested:
                type: array
                items:
                  $ref: '#/components/schemas/DTO1Flat'
      responses:
        "200":
          description: get successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedDTO'
    post:
      tags:
      - Sample_CRUD_APIProvider-Home
      summary: create
      description: ""
      operationId: Home-create
      requestBody:
        description: Message payload (content)
        content:
          application/json:
            schema:
              type: object
              properties:
                primaryIntegerKey:
                  type: integer
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                    target="_blank">Id Element</a>
                  format: int32
                atLeastOneString:
                  minItems: 1
                  type: array
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
                  items:
                    type: string
              description: request body elements for create
      responses:
        "200":
          description: create successful execution
          content:
            application/json:
              schema:
                minItems: 1
                type: array
                items:
                  $ref: '#/components/schemas/NestedDTO'
components:
  schemas:
    DTO1Flat:
      type: object
      properties:
        dtoKey:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
        dtoValue:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
    DTO1Array:
      type: array
      items:
        type: object
        properties:
          dtoKey1a:
            type: integer
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
              target="_blank">Id Element</a>
            format: int32
          dtoValue1a:
            type: string
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
    NestedDTO:
      type: object
      properties:
        dtoKey:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
          nullable: true
        dto1Nested:
          type: array
          items:
            $ref: '#/components/schemas/DTO1Flat'
    DTO2WithAPL:
      type: array
      items:
        type: object
        properties:
          a1:
            type: integer
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
              target="_blank">Id Element</a>
            format: int32
            nullable: true
          a2:
            type: string
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
    TestDTO:
      type: object
      properties:
        noDTOButInt:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
