openapi: 3.0.1
info:
  title: HTTPMultipleBindingsTest
  version: "1.0"
servers:
- url: /providerEndpoint02
- url: /providerEndpoint03
tags:
- name: HelloHTTPEndpointNoBinding2-Home
  externalDocs:
    description: HTTPSampleContract01 contract
    url: ""
- name: HelloHTTPEndpointNoBinding3-Home
  externalDocs:
    description: HTTPSampleContract01 contract
    url: ""
- name: HelloHTTPEndpointNoBinding3-Subresource1
  externalDocs:
    description: HTTPSampleContract01 contract
    url: ""
paths:
  /HTTPSampleContract00:
    get:
      tags:
      - HTTPSampleContract00
      summary: getOperation
      description: ""
      operationId: getOperation
      parameters:
      - name: aQueryParameter
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
      - name: abc
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
      responses:
        "200":
          description: getOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedResponseDTR'
    put:
      tags:
      - HTTPSampleContract00
      summary: putOperation
      description: ""
      operationId: putOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatParameterTree'
      responses:
        "200":
          description: putOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedResponseDTR'
    post:
      tags:
      - HTTPSampleContract00
      summary: createOperation
      description: ""
      operationId: createOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NestedParameterTree'
      responses:
        "200":
          description: createOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlatResponseDTR'
    delete:
      tags:
      - HTTPSampleContract00
      summary: deleteOperation
      description: ""
      operationId: deleteOperation
      parameters:
      - name: Parameter1
        in: query
        description: Type reference null
        schema:
          $ref: '#/components/schemas/FlatParameterTree'
      responses:
        "200":
          description: deleteOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedResponseDTR'
    patch:
      tags:
      - HTTPSampleContract00
      summary: patchOperation
      description: ""
      operationId: patchOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatParameterTree'
      responses:
        "200":
          description: patchOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlatParameterTree'
  /Home: {}
  /:
    get:
      tags:
      - HelloHTTPEndpointNoBinding3-Home
      summary: getOperation
      description: ""
      operationId: Home-getOperation
      parameters:
      - name: abc
        in: cookie
        description: Type reference abc
        schema:
          $ref: '#/components/schemas/AtomicParameter'
      responses:
        "200":
          description: getOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedResponseDTR'
    put:
      tags:
      - HelloHTTPEndpointNoBinding3-Home
      summary: createOperation
      description: ""
      operationId: Home-createOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NestedParameterTree'
      responses:
        "200":
          description: createOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlatResponseDTR'
    post:
      tags:
      - HelloHTTPEndpointNoBinding3-Home
      summary: putOperation
      description: ""
      operationId: Home-putOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatParameterTree'
      responses:
        "200":
          description: putOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedResponseDTR'
  /subresource1:
    put:
      tags:
      - HelloHTTPEndpointNoBinding3-Subresource1
      summary: createOperation
      description: ""
      operationId: Subresource1-createOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NestedParameterTree'
      responses:
        "200":
          description: createOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlatResponseDTR'
    post:
      tags:
      - HelloHTTPEndpointNoBinding3-Subresource1
      summary: putOperation
      description: ""
      operationId: Subresource1-putOperation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatParameterTree'
      responses:
        "200":
          description: putOperation successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedResponseDTR'
components:
  schemas:
    FlatParameterTree:
      type: object
      properties:
        id:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
        md:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
        dInt:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
        lString:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/LinkElement"
            target="_blank">Link Element</a>
        dLong:
          type: number
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        anonymous1:
          type: boolean
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
    NestedParameterTree:
      type: object
      properties:
        npt1:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        npt2:
          $ref: '#/components/schemas/FlatParameterTree'
    FlatResponseDTR:
      type: object
      properties:
        fr1:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
        fr2:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
    NestedResponseDTR:
      type: object
      properties:
        r1:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
        r2:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/LinkElement"
            target="_blank">Link Element</a>
        anonymous2:
          $ref: '#/components/schemas/FlatResponseDTR'
    AtomicParameter:
      type: object
      properties:
        abc:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
    AtomicParameterList:
      type: object
      properties:
        abc:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
        def:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          format: int32
