openapi: 3.0.1
info:
  title: HTTPVerbAndDataTypeMappingTest1
  description: 'API Test Case: HTTPVerbAndDataTypeMappingTest PUBLIC_API FRONTEND_INTEGRATIONBACKEND_INTEGRATION'
  version: "1.0"
servers: []
tags:
- name: SampleEntityInformationHolder
  externalDocs:
    description: SampleEntityInformationHolder contract, Master Data Holder role
    url: https://microservice-api-patterns.org/patterns/responsibility/informationHolderEndpointTypes/MasterDataHolder.html
paths:
  /SampleEntityInformationHolder:
    summary: data-oriented endpoint, long-lived
    get:
      tags:
      - SampleEntityInformationHolder
      summary: getInlinedParameters
      description: ""
      operationId: getInlinedParameters
      parameters:
      - name: primaryIntegerKey
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
          target="_blank">Id Element</a>
        required: true
        schema:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
      - name: atLeastOneString
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: array
          items:
            minItems: 1
            type: array
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
            items:
              type: string
      responses:
        "200":
          description: getInlinedParameters successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  mdKey:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
                      target="_blank">Metadata Element</a>
                    format: int32
                    nullable: true
                  innerDTO:
                    type: array
                    items:
                      $ref: '#/components/schemas/FlatDTO'
    put:
      tags:
      - SampleEntityInformationHolder
      summary: testInlinedParameters (write only method)
      description: '[State Creation Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateCreationOperation.html).'
      operationId: testInlinedParameters
      requestBody:
        description: Message payload (content)
        content:
          application/json:
            schema:
              type: object
              properties:
                primaryIntegerKey:
                  type: integer
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
                    target="_blank">Id Element</a>
                  format: int32
                atLeastOneString:
                  minItems: 1
                  type: array
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
                  items:
                    type: string
              description: request body elements for testInlinedParameters
      responses:
        "200":
          description: testInlinedParameters successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  mdKey:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
                      target="_blank">Metadata Element</a>
                    format: int32
                    nullable: true
                  innerDTO:
                    type: array
                    items:
                      $ref: '#/components/schemas/FlatDTO'
    delete:
      tags:
      - SampleEntityInformationHolder
      summary: deleteExtractedParameters
      description: ""
      operationId: deleteExtractedParameters
      parameters:
      - name: requestMessageWithTypeReference
        in: query
        description: Type reference requestMessageWithTypeReference
        schema:
          $ref: '#/components/schemas/FlatDTO'
      responses:
        "200":
          description: deleteExtractedParameters successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedDTO'
    patch:
      tags:
      - SampleEntityInformationHolder
      summary: testExtractedParameters (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: testExtractedParameters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatDTO'
      responses:
        "200":
          description: testExtractedParameters successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedDTO'
components:
  schemas:
    FlatDTO:
      type: object
      properties:
        idKey:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
        sampleValue:
          minItems: 1
          type: array
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          items:
            type: string
    NestedDTO:
      type: object
      properties:
        mdKey:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
          format: int32
          nullable: true
        innerDTO:
          type: array
          items:
            $ref: '#/components/schemas/FlatDTO'
