openapi: 3.0.1
info:
  title: HTTPVerbAndDataTypeMappingTest2
  description: 'API Test Case: HTTPVerbAndDataTypeMappingTest PUBLIC_API FRONTEND_INTEGRATIONBACKEND_INTEGRATION'
  version: "1.0"
servers:
- url: http://localhost:8080
- url: http://localhost:8080
tags:
- name: SampleEntityInformationHolderProvider1-SampleEntityInformationHolderHome
  externalDocs:
    description: SampleEntityInformationHolder contract, Master Data Holder role
    url: https://microservice-api-patterns.org/patterns/responsibility/informationHolderEndpointTypes/MasterDataHolder.html
- name: SampleEntityInformationHolderProvider2-SampleEntityInformationHolderHome2
  externalDocs:
    description: SampleEntityInformationHolder contract, Master Data Holder role
    url: https://microservice-api-patterns.org/patterns/responsibility/informationHolderEndpointTypes/MasterDataHolder.html
- name: SampleEntityInformationHolderProvider2-SampleEntityInformationHolderHome2_testInlinedParameters
  externalDocs:
    description: SampleEntityInformationHolder contract, Master Data Holder role
    url: https://microservice-api-patterns.org/patterns/responsibility/informationHolderEndpointTypes/MasterDataHolder.html
- name: SampleEntityInformationHolderProvider2-SampleEntityInformationHolderHome2_deleteExtractedParameters
  externalDocs:
    description: SampleEntityInformationHolder contract, Master Data Holder role
    url: https://microservice-api-patterns.org/patterns/responsibility/informationHolderEndpointTypes/MasterDataHolder.html
paths:
  /sampleEntityInformationHolderHome:
    summary: data-oriented endpoint, long-lived
    get:
      tags:
      - SampleEntityInformationHolderProvider1-SampleEntityInformationHolderHome
      summary: getInlinedParameters
      description: ""
      operationId: SampleEntityInformationHolderHome-getInlinedParameters
      parameters:
      - name: primaryIntegerKey
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
          target="_blank">Id Element</a>
        required: true
        schema:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
      - name: atLeastOneString
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: array
          items:
            minItems: 1
            type: array
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
            items:
              type: string
      responses:
        "200":
          description: getInlinedParameters successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  mdKey:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
                      target="_blank">Metadata Element</a>
                    format: int32
                    nullable: true
                  innerDTO:
                    type: array
                    items:
                      $ref: '#/components/schemas/FlatDTO'
    post:
      tags:
      - SampleEntityInformationHolderProvider1-SampleEntityInformationHolderHome
      summary: testInlinedParameters (write only method)
      description: '[State Creation Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateCreationOperation.html).'
      operationId: SampleEntityInformationHolderHome-testInlinedParameters
      parameters:
      - name: primaryIntegerKey
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
          target="_blank">Id Element</a>
        required: true
        schema:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
      - name: atLeastOneString
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: array
          items:
            minItems: 1
            type: array
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
            items:
              type: string
      responses:
        "200":
          description: testInlinedParameters successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  mdKey:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
                      target="_blank">Metadata Element</a>
                    format: int32
                    nullable: true
                  innerDTO:
                    type: array
                    items:
                      $ref: '#/components/schemas/FlatDTO'
    delete:
      tags:
      - SampleEntityInformationHolderProvider1-SampleEntityInformationHolderHome
      summary: deleteExtractedParameters
      description: ""
      operationId: SampleEntityInformationHolderHome-deleteExtractedParameters
      parameters:
      - name: requestMessageWithTypeReference
        in: cookie
        description: Type reference requestMessageWithTypeReference
        schema:
          $ref: '#/components/schemas/FlatDTO'
      responses:
        "200":
          description: deleteExtractedParameters successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedDTO'
    patch:
      tags:
      - SampleEntityInformationHolderProvider1-SampleEntityInformationHolderHome
      summary: testExtractedParameters (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: SampleEntityInformationHolderHome-testExtractedParameters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatDTO'
      responses:
        "200":
          description: testExtractedParameters successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedDTO'
  /sampleEntityInformationHolderHome2:
    summary: data-oriented endpoint, long-lived
    post:
      tags:
      - SampleEntityInformationHolderProvider2-SampleEntityInformationHolderHome2
      summary: testExtractedParameters (read and write method)
      description: '[State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html).'
      operationId: SampleEntityInformationHolderHome2-testExtractedParameters
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlatDTO'
      responses:
        "200":
          description: testExtractedParameters successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedDTO'
  /sampleEntityInformationHolderHome2/{primaryIntegerKey}:
    summary: data-oriented endpoint, long-lived
    get:
      tags:
      - SampleEntityInformationHolderProvider2-SampleEntityInformationHolderHome2_testInlinedParameters
      summary: getInlinedParameters
      description: ""
      operationId: SampleEntityInformationHolderHome2_testInlinedParameters-getInlinedParameters
      parameters:
      - name: primaryIntegerKey
        in: path
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
          target="_blank">Id Element</a>
        required: true
        schema:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
      - name: atLeastOneString
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: array
          items:
            minItems: 1
            type: array
            description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
              target="_blank">Data Element</a>
            items:
              type: string
      responses:
        "200":
          description: getInlinedParameters successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  mdKey:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
                      target="_blank">Metadata Element</a>
                    format: int32
                    nullable: true
                  innerDTO:
                    type: array
                    items:
                      $ref: '#/components/schemas/FlatDTO'
    put:
      tags:
      - SampleEntityInformationHolderProvider2-SampleEntityInformationHolderHome2_testInlinedParameters
      summary: testInlinedParameters (write only method)
      description: '[State Creation Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateCreationOperation.html).'
      operationId: SampleEntityInformationHolderHome2_testInlinedParameters-testInlinedParameters
      parameters:
      - name: primaryIntegerKey
        in: path
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
          target="_blank">Id Element</a>
        required: true
        schema:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
      requestBody:
        description: Message payload (content)
        content:
          application/json:
            schema:
              type: object
              properties:
                atLeastOneString:
                  minItems: 1
                  type: array
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
                  items:
                    type: string
              description: request body elements for testInlinedParameters
      responses:
        "200":
          description: testInlinedParameters successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  mdKey:
                    type: integer
                    description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
                      target="_blank">Metadata Element</a>
                    format: int32
                    nullable: true
                  innerDTO:
                    type: array
                    items:
                      $ref: '#/components/schemas/FlatDTO'
    parameters:
    - name: primaryIntegerKey
      in: path
      required: true
      schema:
        type: string
  /sampleEntityInformationHolderHome2/{requestMessageWithTypeReference}:
    summary: data-oriented endpoint, long-lived
    delete:
      tags:
      - SampleEntityInformationHolderProvider2-SampleEntityInformationHolderHome2_deleteExtractedParameters
      summary: deleteExtractedParameters
      description: ""
      operationId: SampleEntityInformationHolderHome2_deleteExtractedParameters-deleteExtractedParameters
      parameters:
      - name: requestMessageWithTypeReference
        in: path
        description: Type reference requestMessageWithTypeReference
        required: true
        schema:
          $ref: '#/components/schemas/FlatDTO'
      responses:
        "200":
          description: deleteExtractedParameters successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestedDTO'
    parameters:
    - name: requestMessageWithTypeReference
      in: path
      required: true
      schema:
        type: string
components:
  schemas:
    FlatDTO:
      type: object
      properties:
        idKey:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/IdElement"
            target="_blank">Id Element</a>
          format: int32
        sampleValue:
          minItems: 1
          type: array
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
          items:
            type: string
    NestedDTO:
      type: object
      properties:
        mdKey:
          type: integer
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/MetadataElement"
            target="_blank">Metadata Element</a>
          format: int32
          nullable: true
        innerDTO:
          type: array
          items:
            $ref: '#/components/schemas/FlatDTO'
