openapi: 3.0.1
info:
  title: SoadDemo
  version: "1.0"
servers:
- url: http://localhost:8080
tags:
- name: SampleIntegrationScenarioRealizationEndpointProvider-Home
  externalDocs:
    description: The role of this endpoint, offering a SampleIntegrationScenarioRealizationEndpoint
      contract, is Information Holder Resource pattern
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
- name: SampleIntegrationScenarioRealizationEndpointProvider-Home_deleteSomeBusinessObject
  externalDocs:
    description: The role of this endpoint, offering a SampleIntegrationScenarioRealizationEndpoint
      contract, is Information Holder Resource pattern
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
- name: SampleIntegrationScenarioRealizationEndpointProvider-Resource2
  externalDocs:
    description: The role of this endpoint, offering a SampleIntegrationScenarioRealizationEndpoint
      contract, is Information Holder Resource pattern
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
- name: SampleIntegrationScenarioRealizationEndpointProvider-Resource3
  externalDocs:
    description: The role of this endpoint, offering a SampleIntegrationScenarioRealizationEndpoint
      contract, is Information Holder Resource pattern
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /Home:
    summary: general data-oriented endpoint
    get:
      tags:
      - SampleIntegrationScenarioRealizationEndpointProvider-Home
      summary: read only
      description: This operation realizes the [Retrieval Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/RetrievalOperation.html)
        pattern.
      operationId: Home-readSomeBusinessObject
      parameters:
      - name: queryFilter
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: readSomeBusinessObject successful execution
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SomeBusinessObjectDTO'
    put:
      tags:
      - SampleIntegrationScenarioRealizationEndpointProvider-Home
      summary: write only
      description: This operation realizes the [State Creation Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateCreationOperation.html)
        pattern.
      operationId: Home-createSomeBusinessObject
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SomeBusinessObjectDTO'
      responses:
        "200":
          description: createSomeBusinessObject successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  resourceId:
                    type: string
    post:
      tags:
      - SampleIntegrationScenarioRealizationEndpointProvider-Home
      description: unspecified operation responsibility
      operationId: Home-doSomething
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dataTransferObject:
                  type: string
      responses:
        "200":
          description: doSomething successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  doSomethingResponseBody:
                    type: string
  /{resourceId}:
    summary: general data-oriented endpoint
    delete:
      tags:
      - SampleIntegrationScenarioRealizationEndpointProvider-Home_deleteSomeBusinessObject
      summary: ""
      description: unspecified operation responsibility
      operationId: Home_deleteSomeBusinessObject-deleteSomeBusinessObject
      parameters:
      - name: resourceId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: deleteSomeBusinessObject successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  successFlag:
                    type: boolean
    parameters:
    - name: resourceId
      in: path
      required: true
      schema:
        type: string
  /Resource2:
    summary: general data-oriented endpoint
    get:
      tags:
      - SampleIntegrationScenarioRealizationEndpointProvider-Resource2
      summary: read only
      description: This operation realizes the [Retrieval Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/RetrievalOperation.html)
        pattern.
      operationId: Resource2-findAll
      parameters:
      - name: queryFilter
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: findAll successful execution
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleIntegrationScenarioRealizationEndpointDTO'
    post:
      tags:
      - SampleIntegrationScenarioRealizationEndpointProvider-Resource2
      summary: read and write
      description: This operation realizes the [State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html)
        pattern.
      operationId: Resource2-updateSomeBusinessObject
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SomeBusinessObjectDTO'
      responses:
        "200":
          description: updateSomeBusinessObject successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SomeBusinessObjectDTO'
  /Resource3:
    summary: general data-oriented endpoint
    get:
      tags:
      - SampleIntegrationScenarioRealizationEndpointProvider-Resource3
      summary: read only
      description: This operation realizes the [Retrieval Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/RetrievalOperation.html)
        pattern.
      operationId: Resource3-findById
      parameters:
      - name: resourceId
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: findById successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleIntegrationScenarioRealizationEndpointDTO'
  /SampleIntegrationScenarioFlowEndpoint:
    summary: activity-oriented endpoint
    post:
      tags:
      - SampleIntegrationScenarioFlowEndpoint
      summary: ""
      description: unspecified operation responsibility
      operationId: cRUDSomeBusinessObject
      parameters: []
      responses:
        "200":
          description: cRUDSomeBusinessObject successful execution
          content:
            application/json:
              schema:
                type: object
    patch:
      tags:
      - SampleIntegrationScenarioFlowEndpoint
      summary: read and write
      description: This operation realizes the [State Transition Operation](https://microservice-api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html)
        pattern.
      operationId: doSomething
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doSomethingRequestBody:
                  type: string
                desiredElements:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: doSomething successful execution
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    SomeBusinessObjectDTO:
      type: object
      properties:
        someBusinessObject:
          type: string
    SampleIntegrationScenarioRealizationEndpointDTO:
      type: object
      properties:
        sampleIntegrationScenarioRealizationEndpoint:
          type: string
